name: deploy

on:
  push:
    branches: 
        - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm i
        npm run build:prod
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
          target_branch: gh-pages
          build_dir: dist/ng-demo
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PAT: ${{ secrets.GH_PAT }}
